name: Release on JFrog
on:
  push:
    tags:
      - "v*"

jobs:
  documentation:
    name: Publish package to JFrog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
        # Install a specific version of uv.
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        run: uv sync --index="https://${{ secrets.JFROG_USER}}:${{ secrets.JFROG_TOKEN }}@quera.jfrog.io/artifactory/api/pypi/kirin/simple/ https://${{ secrets.JFROG_USER}}:${{ secrets.JFROG_TOKEN }}@quera.jfrog.io/artifactory/api/pypi/quera-pypi-algo/simple/"
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish --publish-url https://quera.jfrog.io/artifactory/api/pypi/bloqade-internal --username ${{ secrets.JFROG_USER }} --password ${{ secrets.JFROG_TOKEN }}
